version: '3.1'
  
services:
  mysql1:
    image: mysql:latest
    container_name: mysql1
    hostname: mysql1
    environment:
        MYSQL_USER: pucsd
        MYSQL_PASSWORD: pucsd
    ports: ["3307:3306"]
    restart: always

  mysql2:
    image: mysql:latest
    container_name: mysql2
    hostname: mysql2
    environment:
       MYSQL_USER: pucsd
       MYSQL_PASSWORD: pucsd
    ports: ["3308:3306"]
    restart: always

  node3:
    image: mysql:latest
    container_name: node3
    hostname: node3
    environment:
       MYSQL_USER: pucsd
       MYSQL_PASSWORD: pucsd
    ports: ["3309:3306"]
    restart: always
